# Generated by Django 5.0.7 on 2025-02-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(blank=True, help_text='头像图片的存储路径', max_length=255, null=True, verbose_name='头像路径'),
        ),
    ]
