# Generated by Django 5.0.7 on 2025-02-06 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='图片的显示名称，可选', max_length=255, null=True, verbose_name='图片名称')),
                ('file', models.ImageField(help_text='上传的图片文件', upload_to='images/%Y/%m/', verbose_name='图片文件')),
                ('description', models.TextField(blank=True, help_text='关于图片的详细描述', verbose_name='图片描述')),
                ('image_type', models.CharField(choices=[('avatar', '头像'), ('article', '文章图片'), ('building', '建筑物图片'), ('other', '其他')], default='other', help_text='图片的用途类型', max_length=20, verbose_name='图片类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='图片创建的时间', verbose_name='创建时间')),
                ('creator', models.ForeignKey(help_text='图片的创建者', on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'ordering': ['-created_at'],
            },
        ),
    ]
