# Generated by Django 5.0.7 on 2025-02-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, help_text='关于图片的详细描述', null=True, verbose_name='图片描述'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.CharField(help_text='图片文件的存储路径', max_length=255, verbose_name='图片路径'),
        ),
    ]
