# Generated by Django 5.0.7 on 2025-02-06 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='建筑物名称')),
                ('description', models.TextField(verbose_name='建筑物描述')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.CharField(max_length=100, verbose_name='建筑物分类')),
                ('image_id', models.IntegerField(blank=True, help_text='关联到 Image 模型的 ID', null=True, verbose_name='建筑物图片ID')),
                ('model', models.FileField(blank=True, null=True, upload_to='builders/models/', verbose_name='建筑物模型文件')),
                ('json', models.TextField(blank=True, null=True, verbose_name='建筑物的 JSON 描述')),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='建筑物标签')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '建筑',
                'verbose_name_plural': '建筑',
                'permissions': [('can_edit_builder', 'Can edit builder')],
            },
        ),
    ]
