# Generated by Django 5.0.7 on 2025-02-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builder',
            options={'ordering': ['-created_at'], 'verbose_name': '建筑物', 'verbose_name_plural': '建筑物'},
        ),
        migrations.RemoveField(
            model_name='builder',
            name='image_id',
        ),
        migrations.AddField(
            model_name='builder',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='建筑物图片路径'),
        ),
    ]
