# Generated by Django 5.0.7 on 2025-02-06 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder', '0001_initial'),
        ('public', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=10, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否精选')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('tags', models.CharField(blank=True, help_text='多个标签用逗号分隔', max_length=200, verbose_name='标签')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='builder.builder', verbose_name='关联建筑')),
                ('content_images', models.ManyToManyField(blank=True, related_name='article_contents', to='public.image', verbose_name='内容图片')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_covers', to='public.image', verbose_name='封面图片')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='article_art_created_d3bafd_idx'), models.Index(fields=['status', '-created_at'], name='article_art_status_7da024_idx')],
            },
        ),
    ]
