# Generated by Django 5.0.7 on 2025-02-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_images',
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='封面图片路径'),
        ),
    ]
