# Generated by Django 5.0.7 on 2025-02-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_content_images_and_more'),
        ('builder', '0002_alter_builder_options_remove_builder_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='draft_saved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='草稿保存时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='builder.builder', verbose_name='关联建筑'),
        ),
    ]
