# Generated by Django 5.0.7 on 2025-02-16 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_draft_saved_at_article_published_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_records', to='article.article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文章点赞记录',
                'verbose_name_plural': '文章点赞记录',
                'ordering': ['-created_at'],
                'unique_together': {('article', 'user')},
            },
        ),
    ]
