# Generated by Django 5.0.7 on 2025-01-12 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('register_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('signature', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
