# Generated by Django 5.0.7 on 2025-02-06 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='统计日期')),
                ('total_users', models.IntegerField(default=0, verbose_name='总用户数')),
                ('new_users', models.IntegerField(default=0, verbose_name='新增用户数')),
                ('active_users', models.IntegerField(default=0, verbose_name='活跃用户数')),
                ('new_articles', models.IntegerField(default=0, verbose_name='新增文章数')),
                ('new_comments', models.IntegerField(default=0, verbose_name='新增评论数')),
                ('new_builders', models.IntegerField(default=0, verbose_name='新增建筑数')),
                ('total_views', models.IntegerField(default=0, verbose_name='总浏览量')),
                ('total_likes', models.IntegerField(default=0, verbose_name='总点赞数')),
                ('api_calls', models.IntegerField(default=0, verbose_name='API调用次数')),
                ('avg_response_time', models.FloatField(default=0, verbose_name='平均响应时间')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误次数')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='APIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=255, verbose_name='访问路径')),
                ('status_code', models.IntegerField(verbose_name='状态码')),
                ('response_time', models.FloatField(verbose_name='响应时间(ms)')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='请求数据')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='访问用户')),
            ],
            options={
                'verbose_name': 'API访问日志',
                'verbose_name_plural': 'API访问日志',
                'indexes': [models.Index(fields=['user', '-timestamp'], name='analytics_a_user_id_c4fd5c_idx'), models.Index(fields=['path', '-timestamp'], name='analytics_a_path_8d7f7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PopularContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('article', '文章'), ('builder', '建筑'), ('comment', '评论')], max_length=20, verbose_name='内容类型')),
                ('content_id', models.PositiveIntegerField(verbose_name='内容ID')),
                ('title', models.CharField(max_length=200, verbose_name='内容标题')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('score', models.FloatField(default=0, verbose_name='热度分数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '热门内容',
                'verbose_name_plural': '热门内容',
                'indexes': [models.Index(fields=['-score'], name='analytics_p_score_cc2791_idx'), models.Index(fields=['content_type', '-score'], name='analytics_p_content_6aa58c_idx')],
                'unique_together': {('content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('view', '查看'), ('create', '创建'), ('update', '更新'), ('delete', '删除'), ('like', '点赞'), ('comment', '评论')], max_length=20, verbose_name='行为类型')),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='额外数据')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
                'indexes': [models.Index(fields=['user', '-timestamp'], name='analytics_u_user_id_6e030d_idx'), models.Index(fields=['action_type', '-timestamp'], name='analytics_u_action__aab89a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_articles', models.IntegerField(default=0, verbose_name='发布文章数')),
                ('total_article_views', models.IntegerField(default=0, verbose_name='文章总浏览量')),
                ('total_article_likes', models.IntegerField(default=0, verbose_name='文章获赞数')),
                ('total_builders', models.IntegerField(default=0, verbose_name='创建建筑数')),
                ('total_comments', models.IntegerField(default=0, verbose_name='评论数')),
                ('total_comment_likes', models.IntegerField(default=0, verbose_name='评论获赞数')),
                ('last_active_time', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('active_days', models.IntegerField(default=0, verbose_name='活跃天数')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户统计',
                'verbose_name_plural': '用户统计',
                'indexes': [models.Index(fields=['-total_articles'], name='analytics_u_total_a_99d499_idx'), models.Index(fields=['-total_article_views'], name='analytics_u_total_a_c89b11_idx'), models.Index(fields=['-active_days'], name='analytics_u_active__43c916_idx')],
            },
        ),
    ]
